const tracks = [
  { id: "kick", name: "キック", icon: "●", color: "#ff3cac" },
  { id: "snare", name: "スネア", icon: "◎", color: "#ffbd2e" },
  { id: "clap", name: "クラップ", icon: "👏", color: "#ff8b32" },
  { id: "closedHat", name: "クローズHH", icon: "◉", color: "#33d6c8" },
  { id: "openHat", name: "オープンHH", icon: "◌", color: "#23a9df" },
  { id: "lowTom", name: "ロータム", icon: "▣", color: "#38e054" },
  { id: "highTom", name: "ハイタム", icon: "▢", color: "#79ef65" },
  { id: "perc", name: "パーカッション", icon: "✕", color: "#9c5cff" }
];

const presets = {
  basic8: { category:"基本", name:"基本の8ビート", subtitle:"ロック・ポップス", bpm:100, lesson:"ハイハットが8分音符を刻み、スネアが2拍目と4拍目に入る基本形だよ。", pattern:{kick:[0,8],snare:[4,12],closedHat:[0,2,4,6,8,10,12,14]} },
  rock8: { category:"ロック", name:"ロック8ビート", subtitle:"力強い定番", bpm:116, lesson:"キックを増やすことで、基本の8ビートより前へ進む力が強くなるよ。", pattern:{kick:[0,3,8,10],snare:[4,12],closedHat:[0,2,4,6,8,10,12,14],openHat:[14]} },
  punk: { category:"ロック", name:"パンクビート", subtitle:"速い8ビート", bpm:168, lesson:"速いテンポと連続したキックで、勢いのあるパンクらしいビートになるよ。", pattern:{kick:[0,2,4,6,8,10,12,14],snare:[4,12],closedHat:[0,2,4,6,8,10,12,14]} },
  halfTime: { category:"基本", name:"ハーフタイム", subtitle:"大きく重いノリ", bpm:82, lesson:"スネアを3拍目だけに置くと、同じテンポでも半分の速さに感じるよ。", pattern:{kick:[0,7,10],snare:[8],closedHat:[0,2,4,6,8,10,12,14]} },
  fourFloor: { category:"ダンス", name:"4つ打ち", subtitle:"ハウス・テクノ", bpm:124, lesson:"キックが毎拍鳴り、裏拍のハイハットがダンスの脈を作るよ。", pattern:{kick:[0,4,8,12],clap:[4,12],closedHat:[2,6,10,14],openHat:[6,14]} },
  disco: { category:"ダンス", name:"ディスコ", subtitle:"華やかな4つ打ち", bpm:118, lesson:"4つ打ちに開いたハイハットと細かい音を重ねると、ディスコらしい躍動感が出るよ。", pattern:{kick:[0,4,8,12],snare:[4,12],clap:[4,12],closedHat:[0,2,4,6,8,10,12,14],openHat:[2,6,10,14]} },
  techno: { category:"ダンス", name:"テクノ", subtitle:"機械的な反復", bpm:132, lesson:"規則的なキックと短いハイハットの反復が、機械的で安定したグルーヴを作るよ。", pattern:{kick:[0,4,8,12],clap:[4,12],closedHat:[0,2,4,6,8,10,12,14],perc:[3,7,11,15]} },
  drumBass: { category:"ダンス", name:"ドラムンベース", subtitle:"高速ブレイク", bpm:174, lesson:"速いテンポでキックとスネアをずらして置くと、駆け抜けるようなブレイクビートになるよ。", pattern:{kick:[0,7,10],snare:[4,12],closedHat:[0,2,4,6,8,10,12,14],openHat:[15],perc:[3,11]} },
  hiphop: { category:"ヒップホップ", name:"ヒップホップ", subtitle:"重いバックビート", bpm:88, lesson:"少ない音数とキックのずれが、ゆったりしたグルーヴを作っているよ。", pattern:{kick:[0,7,10],snare:[4,12],closedHat:[0,2,4,6,8,10,12,14],perc:[15]} },
  boomBap: { category:"ヒップホップ", name:"ブーンバップ", subtitle:"90年代スタイル", bpm:92, swing:12, lesson:"硬いスネアと少し跳ねたハイハットが、クラシックなヒップホップのノリを作るよ。", pattern:{kick:[0,6,10],snare:[4,12],closedHat:[0,2,4,6,8,10,12,14],perc:[3,11]} },
  trap: { category:"ヒップホップ", name:"トラップ", subtitle:"細かいハイハット", bpm:140, lesson:"細かく刻むハイハットと間のあるキックが、現代的なトラップの緊張感を作るよ。", pattern:{kick:[0,7,11],snare:[8],closedHat:[0,2,4,6,8,9,10,11,12,14,15],openHat:[6],perc:[13]} },
  funk: { category:"グルーヴ", name:"ファンク", subtitle:"16分の細かいノリ", bpm:108, lesson:"16分音符の細かい配置と休符の組み合わせで、跳ねるグルーヴを作るよ。", pattern:{kick:[0,3,7,10],snare:[4,12],clap:[12],closedHat:[0,2,3,4,6,8,10,11,12,14,15],openHat:[7],perc:[5,13]} },
  shuffle: { category:"グルーヴ", name:"シャッフル", subtitle:"跳ねる3連の感覚", bpm:112, swing:36, lesson:"スウィングを強くすると、均等な16分音符が長短に変化して跳ねる感じになるよ。", pattern:{kick:[0,8,11],snare:[4,12],closedHat:[0,2,4,6,8,10,12,14]} },
  reggae: { category:"ワールド", name:"レゲエ", subtitle:"裏拍のアクセント", bpm:78, lesson:"裏拍にハイハットやクラップを置くことで、レゲエ特有のゆったりしたノリが生まれるよ。", pattern:{kick:[0,8],snare:[8],clap:[2,6,10,14],closedHat:[2,6,10,14],openHat:[14]} },
  latin: { category:"ワールド", name:"ラテン", subtitle:"シンコペーション", bpm:116, lesson:"拍の頭以外にも音を置くシンコペーションが、前へ進む躍動感を作るよ。", pattern:{kick:[0,6,10],snare:[4,12],closedHat:[0,2,4,6,8,10,12,14],lowTom:[3,7,11,15],perc:[0,5,8,13]} },
  bossa: { category:"ワールド", name:"ボサノヴァ", subtitle:"やわらかなラテン", bpm:126, lesson:"一定のハイハットとシンコペーションしたキックが、軽く揺れるボサノヴァの感覚を作るよ。", pattern:{kick:[0,6,10],snare:[4,12],closedHat:[0,2,4,6,8,10,12,14],perc:[3,7,11,15]} },
  samba: { category:"ワールド", name:"サンバ", subtitle:"細かい打楽器", bpm:138, lesson:"細かいパーカッションと複数のタムを重ねることで、にぎやかなサンバの推進力が生まれるよ。", pattern:{kick:[0,6,8,14],snare:[4,12],closedHat:[0,2,4,6,8,10,12,14],lowTom:[3,7,11,15],highTom:[2,6,10,14],perc:[0,3,5,8,11,13]} },
  afrobeat: { category:"ワールド", name:"アフロビート", subtitle:"重なり合う反復", bpm:110, lesson:"異なる位置の打楽器パターンが重なることで、複雑だけど踊れるグルーヴになるよ。", pattern:{kick:[0,7,10],snare:[4,12],closedHat:[0,2,4,6,8,10,12,14],lowTom:[3,9,15],perc:[1,5,8,13]} },
  jazzRide: { category:"ジャズ", name:"ジャズスウィング", subtitle:"ライドの跳ね", bpm:132, swing:40, lesson:"強いスウィングと2拍目・4拍目のアクセントで、ジャズらしい跳ねる感覚を表しているよ。", pattern:{kick:[0,8],snare:[4,12],closedHat:[0,3,4,7,8,11,12,15],openHat:[4,12]} },
  breakbeat: { category:"グルーヴ", name:"ブレイクビート", subtitle:"崩したドラムパターン", bpm:108, lesson:"規則的な4つ打ちを崩し、キックとスネアを不規則に配置するとブレイク感が出るよ。", pattern:{kick:[0,6,10,15],snare:[4,12],closedHat:[0,2,4,6,8,10,12,14],openHat:[7],perc:[3,11]} }
};

const state={pattern:Object.fromEntries(tracks.map(t=>[t.id,Array(16).fill(false)])),isPlaying:false,currentStep:0,bpm:100,swing:0,volume:.8,timer:null,audioContext:null,masterGain:null,selectedPreset:null};
const $=s=>document.querySelector(s);
const sequencer=$("#sequencer"),playButton=$("#playButton"),clearButton=$("#clearButton"),bpmInput=$("#bpmInput"),bpmValue=$("#bpmValue"),swingInput=$("#swingInput"),swingValue=$("#swingValue"),volumeInput=$("#volumeInput"),volumeValue=$("#volumeValue"),lessonTitle=$("#lessonTitle"),lessonText=$("#lessonText"),beatCount=$("#beatCount"),subdivisionCount=$("#subdivisionCount"),presetSelect=$("#presetSelect"),rhythmLibrary=$("#rhythmLibrary"),helpDialog=$("#helpDialog");

function buildSequencer(){tracks.forEach(track=>{const row=document.createElement("div");row.className="track-row";row.dataset.track=track.id;row.style.setProperty("--track-color",track.color);const label=document.createElement("div");label.className="track-label";label.innerHTML=`<span class="track-icon">${track.icon}</span><span>${track.name}</span>`;row.append(label);for(let i=0;i<16;i++){const b=document.createElement("button");b.type="button";b.className="step";b.dataset.step=String(i);b.setAttribute("aria-label",`${track.name} ${i+1}番目のステップ`);b.setAttribute("aria-pressed","false");b.addEventListener("click",()=>toggleStep(track.id,i,b));row.append(b)}sequencer.append(row)})}
function buildPresetSelect(){const groups={};Object.entries(presets).forEach(([id,p])=>(groups[p.category]??=[]).push([id,p]));Object.entries(groups).forEach(([category,items])=>{const group=document.createElement("optgroup");group.label=category;items.forEach(([id,p])=>{const option=document.createElement("option");option.value=id;option.textContent=`${p.name} — ${p.subtitle}`;group.append(option)});presetSelect.append(group)});rhythmLibrary.textContent=`全${Object.keys(presets).length}種類：${Object.keys(groups).join("・")}`}
function toggleStep(trackId,i,b){ensureAudio();state.pattern[trackId][i]=!state.pattern[trackId][i];b.classList.toggle("is-active",state.pattern[trackId][i]);b.setAttribute("aria-pressed",String(state.pattern[trackId][i]));state.selectedPreset=null;presetSelect.value="";if(state.pattern[trackId][i])triggerSound(trackId,state.audioContext.currentTime)}
function loadPreset(id){const p=presets[id];if(!p)return;tracks.forEach(t=>state.pattern[t.id].fill(false));Object.entries(p.pattern).forEach(([trackId,steps])=>steps.forEach(i=>state.pattern[trackId][i]=true));state.bpm=p.bpm;state.swing=p.swing??0;state.selectedPreset=id;bpmInput.value=state.bpm;swingInput.value=state.swing;presetSelect.value=id;updateControls();lessonTitle.textContent=p.name;lessonText.textContent=p.lesson;renderPattern()}
function renderPattern(){document.querySelectorAll(".track-row").forEach(row=>row.querySelectorAll(".step").forEach((b,i)=>{const active=state.pattern[row.dataset.track][i];b.classList.toggle("is-active",active);b.setAttribute("aria-pressed",String(active))}))}
function ensureAudio(){if(!state.audioContext){const AC=window.AudioContext||window.webkitAudioContext;state.audioContext=new AC();state.masterGain=state.audioContext.createGain();state.masterGain.gain.value=state.volume;state.masterGain.connect(state.audioContext.destination)}if(state.audioContext.state==="suspended")state.audioContext.resume()}
function noise(){const c=state.audioContext,b=c.createBuffer(1,c.sampleRate*.5,c.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=Math.random()*2-1;return b}
function triggerSound(id,time){const c=state.audioContext,o=state.masterGain;if(!c||!o)return;if(id==="kick"){const osc=c.createOscillator(),g=c.createGain();osc.frequency.setValueAtTime(150,time);osc.frequency.exponentialRampToValueAtTime(42,time+.14);g.gain.setValueAtTime(1,time);g.gain.exponentialRampToValueAtTime(.001,time+.38);osc.connect(g).connect(o);osc.start(time);osc.stop(time+.4);return}if(["snare","clap","closedHat","openHat","perc"].includes(id)){const s=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain();s.buffer=noise();f.type="highpass";const x={snare:[900,.22,.7],clap:[1200,.16,.62],closedHat:[6500,.055,.28],openHat:[5200,.34,.24],perc:[2600,.09,.34]}[id];f.frequency.value=x[0];g.gain.setValueAtTime(x[2],time);g.gain.exponentialRampToValueAtTime(.001,time+x[1]);s.connect(f).connect(g).connect(o);s.start(time);s.stop(time+x[1]+.02);return}const osc=c.createOscillator(),g=c.createGain(),freq=id==="lowTom"?120:190;osc.type="sine";osc.frequency.setValueAtTime(freq,time);osc.frequency.exponentialRampToValueAtTime(freq*.62,time+.16);g.gain.setValueAtTime(.75,time);g.gain.exponentialRampToValueAtTime(.001,time+.28);osc.connect(g).connect(o);osc.start(time);osc.stop(time+.3)}
function stepDurationMs(step){const base=60000/state.bpm/4,r=state.swing/100;return step%2===0?base*(1+r):base*(1-r)}
function playCurrentStep(){document.querySelectorAll(".step.is-current").forEach(s=>s.classList.remove("is-current"));document.querySelectorAll(`.step[data-step="${state.currentStep}"]`).forEach(s=>s.classList.add("is-current"));beatCount.textContent=String(Math.floor(state.currentStep/4)+1);subdivisionCount.textContent=["1","e","&","a"][state.currentStep%4];const time=state.audioContext.currentTime;tracks.forEach(t=>state.pattern[t.id][state.currentStep]&&triggerSound(t.id,time));const current=state.currentStep;state.currentStep=(state.currentStep+1)%16;state.timer=setTimeout(playCurrentStep,stepDurationMs(current))}
function startPlayback(){ensureAudio();state.isPlaying=true;playButton.classList.add("is-playing");playButton.setAttribute("aria-label","停止");playCurrentStep()}
function stopPlayback(){state.isPlaying=false;clearTimeout(state.timer);state.timer=null;state.currentStep=0;playButton.classList.remove("is-playing");playButton.setAttribute("aria-label","再生");document.querySelectorAll(".step.is-current").forEach(s=>s.classList.remove("is-current"));beatCount.textContent="1";subdivisionCount.textContent="e"}
function clearPattern(){tracks.forEach(t=>state.pattern[t.id].fill(false));state.selectedPreset=null;presetSelect.value="";lessonTitle.textContent="自由にビートを作ろう";lessonText.textContent="光るマスをタップすると、その位置で音が鳴るよ。4マスで1拍、16マスで1小節。";renderPattern()}
function updateControls(){bpmValue.textContent=state.bpm;swingValue.textContent=`${state.swing}%`;volumeValue.textContent=`${Math.round(state.volume*100)}%`}
playButton.addEventListener("click",()=>state.isPlaying?stopPlayback():startPlayback());clearButton.addEventListener("click",clearPattern);presetSelect.addEventListener("change",e=>loadPreset(e.target.value));bpmInput.addEventListener("input",e=>{state.bpm=Number(e.target.value);bpmValue.textContent=state.bpm});swingInput.addEventListener("input",e=>{state.swing=Number(e.target.value);swingValue.textContent=`${state.swing}%`});volumeInput.addEventListener("input",e=>{state.volume=Number(e.target.value)/100;volumeValue.textContent=`${e.target.value}%`;if(state.masterGain)state.masterGain.gain.setTargetAtTime(state.volume,state.audioContext.currentTime,.01)});$("#helpButton").addEventListener("click",()=>helpDialog.showModal());$("#closeHelpButton").addEventListener("click",()=>helpDialog.close());helpDialog.addEventListener("click",e=>e.target===helpDialog&&helpDialog.close());document.addEventListener("keydown",e=>{if(e.code==="Space"&&!['INPUT','BUTTON','SELECT'].includes(document.activeElement.tagName)){e.preventDefault();state.isPlaying?stopPlayback():startPlayback()}});
buildSequencer();buildPresetSelect();loadPreset("basic8");