const tracks=[
{id:'kick',name:'Kick',icon:'●',color:'#ff3cac',type:'kick'},{id:'snare',name:'Snare',icon:'◎',color:'#ffbd2e',type:'noise'},{id:'clap',name:'Clap',icon:'👏',color:'#ff8b32',type:'noise'},{id:'rim',name:'Rim Shot',icon:'◍',color:'#ff6b6b',type:'click'},{id:'side',name:'Side Stick',icon:'◐',color:'#f9844a',type:'click'},
{id:'closedHat',name:'Closed HH',icon:'◉',color:'#33d6c8',type:'hat'},{id:'openHat',name:'Open HH',icon:'◌',color:'#23a9df',type:'hat'},{id:'pedalHat',name:'Pedal HH',icon:'⊙',color:'#2ec4b6',type:'hat'},{id:'highTom',name:'High Tom',icon:'▢',color:'#79ef65',type:'tom'},{id:'midTom',name:'Mid Tom',icon:'▣',color:'#57cc99',type:'tom'},{id:'floorTom',name:'Floor Tom',icon:'■',color:'#38e054',type:'tom'},
{id:'crash',name:'Crash',icon:'✦',color:'#ffd166',type:'cymbal'},{id:'ride',name:'Ride',icon:'◒',color:'#f9c74f',type:'cymbal'},{id:'splash',name:'Splash',icon:'✧',color:'#ffe66d',type:'cymbal'},{id:'china',name:'China',icon:'⌁',color:'#e9c46a',type:'cymbal'},{id:'cowbell',name:'Cowbell',icon:'◇',color:'#9c5cff',type:'metal'},
{id:'tambourine',name:'Tambourine',icon:'✺',color:'#b5179e',type:'noise'},{id:'shaker',name:'Shaker',icon:'≋',color:'#7209b7',type:'noise'},{id:'conga',name:'Conga',icon:'⬭',color:'#4cc9f0',type:'tom'},{id:'bongo',name:'Bongo',icon:'◫',color:'#4895ef',type:'tom'},{id:'timbale',name:'Timbale',icon:'◩',color:'#4361ee',type:'tom'},{id:'claves',name:'Claves',icon:'×',color:'#3a0ca3',type:'click'},{id:'woodBlock',name:'Wood Block',icon:'▭',color:'#8338ec',type:'click'},{id:'triangle',name:'Triangle',icon:'△',color:'#c77dff',type:'metal'}];
const presets={
basic8:{category:'基本',name:'基本の8ビート',subtitle:'ロック・ポップス',bpm:100,difficulty:'初級',meter:'4/4',feature:'8分音符のハイハットと2・4拍のスネア',role:'キックが土台、スネアがバックビート、ハイハットが時間を刻む',practice:'BPM 70から、キックとスネアだけ→ハイハット追加',lesson:'多くのロックやポップスの基礎になる定番パターン。',pattern:{kick:[0,8],snare:[4,12],closedHat:[0,2,4,6,8,10,12,14]}},
rock8:{category:'ロック',name:'ロック8ビート',subtitle:'力強い定番',bpm:116,difficulty:'初級',meter:'4/4',feature:'キックを増やした前進感',role:'クラッシュは節目、オープンハイハットは盛り上がりを作る',practice:'4小節目だけクラッシュを足してみよう',lesson:'キックの追加で基本形より強い推進力が生まれる。',pattern:{kick:[0,3,8,10],snare:[4,12],closedHat:[0,2,4,6,8,10,12,14],openHat:[14],crash:[0]}},
punk:{category:'ロック',name:'パンクビート',subtitle:'高速8ビート',bpm:176,difficulty:'中級',meter:'4/4',feature:'高速テンポと連打するキック',role:'クラッシュとハイハットが勢いを支える',practice:'半分のBPMで正確さを作ってから上げる',lesson:'音数を揃えてまっすぐ押し切るビート。',pattern:{kick:[0,2,4,6,8,10,12,14],snare:[4,12],closedHat:[0,2,4,6,8,10,12,14],crash:[0]}},
halfTime:{category:'基本',name:'ハーフタイム',subtitle:'大きく重いノリ',bpm:82,difficulty:'初級',meter:'4/4',feature:'スネアを3拍目に置くことで半分に感じる',role:'間を広く取り、キックの重さを強調する',practice:'通常8ビートと交互に切り替えて体感する',lesson:'同じテンポでもスネア位置で速度感が変わる。',pattern:{kick:[0,7,10],snare:[8],closedHat:[0,2,4,6,8,10,12,14]}},
fourFloor:{category:'EDM',name:'4つ打ち',subtitle:'ハウス・テクノ',bpm:124,difficulty:'初級',meter:'4/4',feature:'毎拍のキックと裏拍ハイハット',role:'キックが一定の脈、クラップが2・4拍を強調',practice:'裏拍のハイハットだけを口で歌ってみよう',lesson:'ダンス音楽の基本となる安定したビート。',pattern:{kick:[0,4,8,12],clap:[4,12],closedHat:[2,6,10,14],openHat:[6,14]}},
disco:{category:'ポップス',name:'ディスコ',subtitle:'華やかな4つ打ち',bpm:118,difficulty:'初級',meter:'4/4',feature:'4つ打ち＋16分系ハイハット',role:'オープンハイハットが裏拍の浮遊感を作る',practice:'クローズとオープンの鳴り分けを聴く',lesson:'明るく踊れる華やかなグルーヴ。',pattern:{kick:[0,4,8,12],snare:[4,12],clap:[4,12],closedHat:[0,2,4,6,8,10,12,14],openHat:[2,6,10,14]}},
techno:{category:'EDM',name:'テクノ',subtitle:'機械的な反復',bpm:132,difficulty:'初級',meter:'4/4',feature:'均等な反復と少ない変化',role:'キックが中心、パーカッションが質感を加える',practice:'1音だけ位置を変えて印象の差を比べる',lesson:'規則性そのものがグルーヴになる。',pattern:{kick:[0,4,8,12],clap:[4,12],closedHat:[0,2,4,6,8,10,12,14],shaker:[3,7,11,15]}},
dnb:{category:'EDM',name:'ドラムンベース',subtitle:'高速ブレイク',bpm:174,difficulty:'上級',meter:'4/4',feature:'高速BPMと崩したキック・スネア',role:'細かいハイハットが速度感を維持する',practice:'BPM 90で配置を理解してから倍にする',lesson:'高速でもバックビートの位置を見失わないのがコツ。',pattern:{kick:[0,7,10],snare:[4,12],closedHat:[0,2,4,6,8,10,12,14],openHat:[15],rim:[3,11]}},
hiphop:{category:'ヒップホップ',name:'ヒップホップ',subtitle:'重いバックビート',bpm:88,difficulty:'初級',meter:'4/4',feature:'少ない音数と後ろに引く感覚',role:'キックのシンコペーションがノリを作る',practice:'スウィングを0→15%で比較する',lesson:'間を活かして重さを出すグルーヴ。',pattern:{kick:[0,7,10],snare:[4,12],closedHat:[0,2,4,6,8,10,12,14],rim:[15]}},
boomBap:{category:'ヒップホップ',name:'ブーンバップ',subtitle:'90年代スタイル',bpm:92,swing:12,difficulty:'中級',meter:'4/4',feature:'硬いスネアと少し跳ねるハイハット',role:'キックとスネアの音色対比が重要',practice:'スウィング量を少しずつ上げて最適点を探す',lesson:'クラシックなヒップホップの代表的な質感。',pattern:{kick:[0,6,10],snare:[4,12],closedHat:[0,2,4,6,8,10,12,14],rim:[3,11]}},
trap:{category:'ヒップホップ',name:'トラップ',subtitle:'細かいハイハット',bpm:140,difficulty:'中級',meter:'4/4',feature:'細かなハイハットロールと間のあるキック',role:'ハイハットが緊張感、808系キックが低音を担当',practice:'まず8分、次に16分の装飾を加える',lesson:'密度の差が現代的なうねりを作る。',pattern:{kick:[0,7,11],snare:[8],closedHat:[0,2,4,6,8,9,10,11,12,14,15],openHat:[6],rim:[13]}},
funk:{category:'ファンク',name:'ファンク',subtitle:'16分の細かいノリ',bpm:108,difficulty:'中級',meter:'4/4',feature:'16分音符と休符の細かな組み合わせ',role:'ゴースト感のあるスネアとハイハットが核',practice:'各拍の「e & a」を声に出して演奏する',lesson:'音を鳴らさない場所もグルーヴの一部。',pattern:{kick:[0,3,7,10],snare:[4,12],clap:[12],closedHat:[0,2,3,4,6,8,10,11,12,14,15],openHat:[7],rim:[5,13]}},
shuffle:{category:'ブルース',name:'シャッフル',subtitle:'跳ねる3連の感覚',bpm:112,swing:36,difficulty:'中級',meter:'4/4',feature:'均等な16分を長短に変える',role:'スウィングしたハイハットがノリを決める',practice:'まっすぐ→スウィングを交互に聴く',lesson:'機械的な均等さから離れると跳ねる感覚が生まれる。',pattern:{kick:[0,8,11],snare:[4,12],closedHat:[0,2,4,6,8,10,12,14]}},
reggae:{category:'ワールド',name:'レゲエ',subtitle:'裏拍のアクセント',bpm:78,difficulty:'初級',meter:'4/4',feature:'裏拍にアクセントを置く',role:'リムやハイハットが裏拍を明確にする',practice:'表拍で手、裏拍で声を出して感じる',lesson:'重心を表拍ではなく裏拍に移す。',pattern:{kick:[0,8],snare:[8],rim:[2,6,10,14],closedHat:[2,6,10,14],openHat:[14]}},
latin:{category:'ラテン',name:'ラテン',subtitle:'シンコペーション',bpm:116,difficulty:'中級',meter:'4/4',feature:'拍の頭以外に音を置くシンコペーション',role:'コンガやクラーベが複数の周期を重ねる',practice:'クラーベだけをループして覚える',lesson:'ずれたアクセントが前進感を作る。',pattern:{kick:[0,6,10],snare:[4,12],closedHat:[0,2,4,6,8,10,12,14],conga:[3,7,11,15],claves:[0,5,8,13]}},
bossa:{category:'ラテン',name:'ボサノヴァ',subtitle:'やわらかなラテン',bpm:126,difficulty:'中級',meter:'4/4',feature:'一定の刻みと柔らかなシンコペーション',role:'サイドスティックが静かな輪郭を作る',practice:'音量を下げて均一に演奏する',lesson:'強く叩かずに流れを保つのがポイント。',pattern:{kick:[0,6,10],side:[4,12],closedHat:[0,2,4,6,8,10,12,14],claves:[3,7,11,15]}},
samba:{category:'ラテン',name:'サンバ',subtitle:'細かい打楽器',bpm:138,difficulty:'上級',meter:'4/4',feature:'複数の打楽器が重なる高密度リズム',role:'シェイカーが流れ、スルド的キックが土台',practice:'楽器を1つずつ追加して重なりを聴く',lesson:'それぞれは単純でも重なると複雑になる。',pattern:{kick:[0,6,8,14],snare:[4,12],shaker:[0,2,4,6,8,10,12,14],floorTom:[3,7,11,15],highTom:[2,6,10,14],tambourine:[0,3,5,8,11,13]}},
afrobeat:{category:'ワールド',name:'アフロビート',subtitle:'重なり合う反復',bpm:110,difficulty:'上級',meter:'4/4',feature:'異なる周期のパーカッションが重なる',role:'反復の層がポリリズム感を作る',practice:'キックを聴きながらクラーベを口ずさむ',lesson:'複数の規則を同時に感じる練習になる。',pattern:{kick:[0,7,10],snare:[4,12],closedHat:[0,2,4,6,8,10,12,14],conga:[3,9,15],claves:[1,5,8,13]}},
jazzRide:{category:'ジャズ',name:'ジャズスウィング',subtitle:'ライドの跳ね',bpm:132,swing:40,difficulty:'中級',meter:'4/4',feature:'ライドのスキップパターンと2・4拍',role:'ライドが時間、ペダルハイハットが2・4拍を示す',practice:'ライドだけでスウィングを感じる',lesson:'強いスウィングとライドの間隔がジャズらしさを作る。',pattern:{kick:[0,8],snare:[4,12],ride:[0,3,4,7,8,11,12,15],pedalHat:[4,12]}},
jazzWaltz:{category:'ジャズ',name:'ジャズワルツ',subtitle:'3拍子スウィング',bpm:144,swing:35,difficulty:'中級',meter:'3/4',feature:'3拍子にスウィングを重ねる',role:'ライドが1-2-3を保ち、スネアが会話する',practice:'「1・2・3」を声に出して回す',lesson:'4拍子とは違う円を描くような流れ。',pattern:{kick:[0],snare:[6],ride:[0,3,4,7,8,11],pedalHat:[4,8]}},
rock68:{category:'ロック',name:'6/8ロック',subtitle:'大きく揺れる',bpm:92,difficulty:'中級',meter:'6/8',feature:'6つの8分音符を2つの大きな拍で感じる',role:'キックが1、スネアが4の位置を強調',practice:'「1-2-3 4-5-6」と数える',lesson:'3連系の大きなうねりを持つロック。',pattern:{kick:[0,6],snare:[6],closedHat:[0,2,4,6,8,10],crash:[0]}},
clave32:{category:'ラテン',name:'3-2クラーベ',subtitle:'ラテンの骨格',bpm:112,difficulty:'中級',meter:'4/4',feature:'前半3打・後半2打のクラーベ',role:'クラーベが他の楽器の基準線になる',practice:'クラーベだけを手拍子で暗記する',lesson:'ラテン音楽の配置を理解する鍵になる。',pattern:{kick:[0,8],claves:[0,3,6,10,12],conga:[2,7,11,15],shaker:[0,2,4,6,8,10,12,14]}},
oddfive:{category:'変拍子',name:'5/4グルーヴ',subtitle:'3+2で感じる',bpm:105,difficulty:'上級',meter:'5/4',feature:'5拍を3拍＋2拍に分ける',role:'キックのアクセントがまとまりを示す',practice:'「1-2-3 / 1-2」と声に出す',lesson:'奇数拍子もグループ分けすると捉えやすい。',pattern:{kick:[0,8,12],snare:[4,16],closedHat:[0,2,4,6,8,10,12,14,16,18]}}
};
const $=s=>document.querySelector(s);const els={sequencer:$('#sequencer'),timeline:$('#timeline'),play:$('#playButton'),clear:$('#clearButton'),save:$('#saveButton'),bpm:$('#bpmInput'),bpmV:$('#bpmValue'),swing:$('#swingInput'),swingV:$('#swingValue'),volume:$('#volumeInput'),volumeV:$('#volumeValue'),preset:$('#presetSelect'),category:$('#categorySelect'),search:$('#presetSearch'),favorite:$('#favoriteButton'),cards:$('#presetCards'),library:$('#rhythmLibrary'),title:$('#lessonTitle'),text:$('#lessonText'),tags:$('#lessonTags'),feature:$('#featureText'),role:$('#roleText'),practice:$('#practiceText'),beat:$('#beatCount'),sub:$('#subdivisionCount'),steps:$('#stepCountSelect'),meter:$('#meterSelect'),metronome:$('#metronomeInput'),help:$('#helpDialog')};
const state={stepCount:16,meter:'4/4',pattern:{},isPlaying:false,currentStep:0,bpm:100,swing:0,volume:.8,timer:null,audioContext:null,masterGain:null,selectedPreset:'basic8',favorites:new Set(JSON.parse(localStorage.getItem('rhythmLabFavorites')||'[]'))};
function resetPattern(){state.pattern=Object.fromEntries(tracks.map(t=>[t.id,Array(state.stepCount).fill(false)]))}function effectiveSteps(){return state.meter==='3/4'||state.meter==='6/8'?12:state.meter==='5/4'?20:state.stepCount}
function buildTimeline(){const n=effectiveSteps();els.timeline.innerHTML='<div></div>'+Array.from({length:n},(_,i)=>`<div class="${i%4===0?'beat-number':''}">${i%4===0?Math.floor(i/4)+1:''}</div>`).join('');els.timeline.style.setProperty('--steps',n)}
function buildSequencer(){const n=effectiveSteps();els.sequencer.innerHTML='';tracks.forEach(track=>{if(!state.pattern[track.id]||state.pattern[track.id].length<n)state.pattern[track.id]=Array(n).fill(false);const row=document.createElement('div');row.className='track-row';row.dataset.track=track.id;row.style.setProperty('--track-color',track.color);row.style.setProperty('--steps',n);row.innerHTML=`<div class="track-label"><span class="track-icon">${track.icon}</span><span>${track.name}</span></div>`;for(let i=0;i<n;i++){const b=document.createElement('button');b.type='button';b.className='step';b.dataset.step=i;b.addEventListener('click',()=>toggleStep(track.id,i,b));row.append(b)}els.sequencer.append(row)});renderPattern();buildTimeline()}
function filteredPresets(){const q=els.search.value.trim().toLowerCase(),cat=els.category.value;return Object.entries(presets).filter(([,p])=>(cat==='all'||p.category===cat)&&(!q||`${p.name} ${p.subtitle} ${p.category} ${p.lesson} ${p.feature}`.toLowerCase().includes(q)))}
function buildCategories(){[...new Set(Object.values(presets).map(p=>p.category))].sort().forEach(c=>els.category.add(new Option(c,c)))}function buildPresetUI(){const list=filteredPresets();els.preset.innerHTML='';list.forEach(([id,p])=>els.preset.add(new Option(`【${p.category}】${p.name}｜${p.subtitle}`,id)));if(list.length&&!list.some(([id])=>id===state.selectedPreset))state.selectedPreset=list[0][0];els.preset.value=state.selectedPreset;els.library.textContent=`${list.length} / 全${Object.keys(presets).length}種類`;els.cards.innerHTML=list.slice(0,12).map(([id,p])=>`<button class="preset-card ${id===state.selectedPreset?'is-selected':''}" data-id="${id}"><span>${p.category}・${p.difficulty}</span><strong>${p.name}</strong><small>${p.subtitle}</small></button>`).join('');els.cards.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>loadPreset(b.dataset.id)))}
function loadPreset(id){const p=presets[id];if(!p)return;state.selectedPreset=id;state.meter=p.meter||'4/4';els.meter.value=state.meter;const n=effectiveSteps();state.pattern=Object.fromEntries(tracks.map(t=>[t.id,Array(n).fill(false)]));Object.entries(p.pattern).forEach(([trackId,steps])=>steps.filter(i=>i<n).forEach(i=>state.pattern[trackId][i]=true));state.bpm=p.bpm;state.swing=p.swing||0;els.bpm.value=state.bpm;els.swing.value=state.swing;updateControls();updateLesson(p);buildSequencer();buildPresetUI();updateFavorite()}
function updateLesson(p){els.title.textContent=p.name;els.text.textContent=p.lesson;els.tags.innerHTML=[p.category,p.meter,p.difficulty,p.swing?`Swing ${p.swing}%`:'ストレート'].map(x=>`<span>${x}</span>`).join('');els.feature.textContent=p.feature;els.role.textContent=p.role;els.practice.textContent=p.practice}
function toggleStep(id,i,b){ensureAudio();state.pattern[id][i]=!state.pattern[id][i];b.classList.toggle('is-active',state.pattern[id][i]);state.selectedPreset=null;if(state.pattern[id][i])triggerSound(id,state.audioContext.currentTime)}function renderPattern(){document.querySelectorAll('.track-row').forEach(row=>row.querySelectorAll('.step').forEach((b,i)=>b.classList.toggle('is-active',!!state.pattern[row.dataset.track]?.[i])))}
function ensureAudio(){if(!state.audioContext){const AC=window.AudioContext||window.webkitAudioContext;state.audioContext=new AC();state.masterGain=state.audioContext.createGain();state.masterGain.gain.value=state.volume;state.masterGain.connect(state.audioContext.destination)}if(state.audioContext.state==='suspended')state.audioContext.resume()}function noiseBuffer(){const c=state.audioContext,b=c.createBuffer(1,c.sampleRate*.5,c.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=Math.random()*2-1;return b}
function triggerSound(id,time){const c=state.audioContext,o=state.masterGain,t=tracks.find(x=>x.id===id);if(!c||!o||!t)return;const idx=tracks.indexOf(t);if(t.type==='kick'){const osc=c.createOscillator(),g=c.createGain();osc.frequency.setValueAtTime(150,time);osc.frequency.exponentialRampToValueAtTime(42,time+.16);g.gain.setValueAtTime(1,time);g.gain.exponentialRampToValueAtTime(.001,time+.4);osc.connect(g).connect(o);osc.start(time);osc.stop(time+.42);return}if(['noise','hat','cymbal'].includes(t.type)){const s=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain();s.buffer=noiseBuffer();f.type='highpass';f.frequency.value=(t.type==='hat'?5200:t.type==='cymbal'?2800:900)+(idx%4)*650;const dur=id==='openHat'||t.type==='cymbal'?.42:id==='shaker'?.08:.16;g.gain.setValueAtTime(t.type==='cymbal'?.28:.52,time);g.gain.exponentialRampToValueAtTime(.001,time+dur);s.connect(f).connect(g).connect(o);s.start(time);s.stop(time+dur+.02);return}const osc=c.createOscillator(),g=c.createGain();osc.type=t.type==='metal'?'triangle':'sine';const freq=t.type==='tom'?95+(idx%6)*28:t.type==='metal'?700+(idx%4)*240:320+(idx%5)*90;osc.frequency.setValueAtTime(freq,time);if(t.type==='tom')osc.frequency.exponentialRampToValueAtTime(freq*.65,time+.16);g.gain.setValueAtTime(.65,time);g.gain.exponentialRampToValueAtTime(.001,time+(t.type==='metal'?.34:.18));osc.connect(g).connect(o);osc.start(time);osc.stop(time+.36)}
function clickSound(time,accent){const c=state.audioContext,g=c.createGain(),osc=c.createOscillator();osc.frequency.value=accent?1200:850;g.gain.setValueAtTime(.18,time);g.gain.exponentialRampToValueAtTime(.001,time+.04);osc.connect(g).connect(state.masterGain);osc.start(time);osc.stop(time+.05)}function stepDurationMs(step){const base=60000/state.bpm/4,r=state.swing/100;return step%2===0?base*(1+r):base*(1-r)}
function playCurrentStep(){const n=effectiveSteps();document.querySelectorAll('.step.is-current').forEach(s=>s.classList.remove('is-current'));document.querySelectorAll(`.step[data-step="${state.currentStep}"]`).forEach(s=>s.classList.add('is-current'));els.beat.textContent=Math.floor(state.currentStep/4)+1;els.sub.textContent=['1','e','&','a'][state.currentStep%4];const time=state.audioContext.currentTime;if(state.metronome&&state.currentStep%4===0)clickSound(time,state.currentStep===0);tracks.forEach(t=>state.pattern[t.id]?.[state.currentStep]&&triggerSound(t.id,time));const current=state.currentStep;state.currentStep=(state.currentStep+1)%n;state.timer=setTimeout(playCurrentStep,stepDurationMs(current))}function start(){ensureAudio();state.isPlaying=true;els.play.classList.add('is-playing');playCurrentStep()}function stop(){state.isPlaying=false;clearTimeout(state.timer);state.currentStep=0;els.play.classList.remove('is-playing');document.querySelectorAll('.step.is-current').forEach(s=>s.classList.remove('is-current'));els.beat.textContent='1';els.sub.textContent='e'}
function clear(){state.pattern=Object.fromEntries(tracks.map(t=>[t.id,Array(effectiveSteps()).fill(false)]));state.selectedPreset=null;els.title.textContent='自由にビートを作ろう';els.text.textContent='24種類の楽器を組み合わせて、自分だけのリズムを作ろう。';els.tags.innerHTML='<span>自由制作</span>';renderPattern();buildPresetUI()}function updateControls(){els.bpmV.textContent=state.bpm;els.swingV.textContent=`${state.swing}%`;els.volumeV.textContent=`${Math.round(state.volume*100)}%`}function updateFavorite(){const on=state.selectedPreset&&state.favorites.has(state.selectedPreset);els.favorite.setAttribute('aria-pressed',String(on));els.favorite.textContent=on?'★ お気に入り済み':'☆ お気に入り'}
function savePattern(){localStorage.setItem('rhythmLabPattern',JSON.stringify({pattern:state.pattern,bpm:state.bpm,swing:state.swing,meter:state.meter,stepCount:state.stepCount}));els.save.textContent='保存済み ✓';setTimeout(()=>els.save.textContent='保存',1200)}function restorePattern(){try{const s=JSON.parse(localStorage.getItem('rhythmLabPattern'));if(!s)return;Object.assign(state,{pattern:s.pattern,bpm:s.bpm,swing:s.swing,meter:s.meter,stepCount:s.stepCount,selectedPreset:null});els.bpm.value=state.bpm;els.swing.value=state.swing;els.meter.value=state.meter;els.steps.value=state.stepCount;updateControls();buildSequencer()}catch{}}
els.play.addEventListener('click',()=>state.isPlaying?stop():start());els.clear.addEventListener('click',clear);els.save.addEventListener('click',savePattern);els.preset.addEventListener('change',e=>loadPreset(e.target.value));els.category.addEventListener('change',buildPresetUI);els.search.addEventListener('input',buildPresetUI);els.bpm.addEventListener('input',e=>{state.bpm=+e.target.value;updateControls()});els.swing.addEventListener('input',e=>{state.swing=+e.target.value;updateControls()});els.volume.addEventListener('input',e=>{state.volume=+e.target.value/100;updateControls();if(state.masterGain)state.masterGain.gain.setTargetAtTime(state.volume,state.audioContext.currentTime,.01)});els.steps.addEventListener('change',e=>{state.stepCount=+e.target.value;clear();buildSequencer()});els.meter.addEventListener('change',e=>{state.meter=e.target.value;clear();buildSequencer()});els.metronome.addEventListener('change',e=>state.metronome=e.target.checked);els.favorite.addEventListener('click',()=>{if(!state.selectedPreset)return;state.favorites.has(state.selectedPreset)?state.favorites.delete(state.selectedPreset):state.favorites.add(state.selectedPreset);localStorage.setItem('rhythmLabFavorites',JSON.stringify([...state.favorites]));updateFavorite()});$('#helpButton').addEventListener('click',()=>els.help.showModal());$('#closeHelpButton').addEventListener('click',()=>els.help.close());els.help.addEventListener('click',e=>{if(e.target===els.help)els.help.close()});document.addEventListener('keydown',e=>{if(e.code==='Space'&&!['INPUT','BUTTON','SELECT'].includes(document.activeElement.tagName)){e.preventDefault();state.isPlaying?stop():start()}});resetPattern();buildCategories();buildPresetUI();loadPreset('basic8');restorePattern();