const drumFills={
 rock1:{name:'王道スネア→タム',genre:'ロック',length:4,difficulty:'初級',description:'4拍目をスネアからタムへ流して次の小節へつなぐ定番フィル。',pattern:{snare:[0,1],highTom:[2],floorTom:[3]},meta:{snare:{0:['accent',116],1:['normal',100]},highTom:{2:['normal',108]},floorTom:{3:['flam',122]}}},
 rock2:{name:'8分タム下降',genre:'ロック',length:8,difficulty:'初級',description:'ハイタムからフロアタムへ下がる分かりやすい8分フィル。',pattern:{snare:[0,1],highTom:[2,3],midTom:[4,5],floorTom:[6,7]},meta:{snare:{0:['accent',112]},floorTom:{7:['flam',124]}}},
 rock3:{name:'16分フルタム',genre:'ロック',length:16,difficulty:'中級',description:'1小節を使ってスネアと3種類のタムを順番に回す。',pattern:{snare:[0,1,2,3],highTom:[4,5,6,7],midTom:[8,9,10,11],floorTom:[12,13,14,15]},meta:{snare:{0:['accent',118]},highTom:{4:['accent',112]},midTom:{8:['accent',114]},floorTom:{12:['accent',118],15:['flam',127]}}},
 pop1:{name:'歌もの控えめフィル',genre:'ポップス',length:4,difficulty:'初級',description:'スネアとハイタムだけで歌を邪魔しない短いフィル。',pattern:{snare:[0,1,2],highTom:[3]},meta:{snare:{0:['ghost',52],1:['normal',88],2:['accent',108]},highTom:{3:['normal',102]}}},
 pop2:{name:'スネア6連風',genre:'ポップス',length:8,difficulty:'中級',description:'弱音から強音へ向かうスネアロール風フィル。',pattern:{snare:[0,1,2,3,4,5,6,7]},meta:{snare:{0:['ghost',42],1:['ghost',48],2:['normal',62],3:['normal',72],4:['normal',82],5:['accent',98],6:['roll',108],7:['flam',124]}}},
 funk1:{name:'ゴースト・ポケット',genre:'ファンク',length:4,difficulty:'中級',description:'弱いスネアを挟み、最後をアクセントで締めるファンク系フィル。',pattern:{snare:[0,1,2,3],kick:[1],openHat:[2]},meta:{snare:{0:['ghost',38],1:['normal',74],2:['ghost',44],3:['flam',116]},kick:{1:['accent',110]},openHat:{2:['accent',96]}}},
 funk2:{name:'リニア・ファンク',genre:'ファンク',length:8,difficulty:'上級',description:'同時打ちを避けてキック・スネア・タムを交互に並べる。',pattern:{kick:[0,4],snare:[1,5],highTom:[2,6],floorTom:[3,7]},meta:{kick:{0:['accent',112]},snare:{1:['ghost',60],5:['accent',108]},floorTom:{7:['flam',120]}}},
 metal1:{name:'高速タムロール',genre:'メタル',length:8,difficulty:'上級',description:'ロール表現を使った高速タム下降フィル。',pattern:{highTom:[0,1],midTom:[2,3],floorTom:[4,5],snare:[6,7]},meta:{highTom:{0:['roll',108]},midTom:{2:['roll',112]},floorTom:{4:['roll',118]},snare:{6:['roll',120],7:['flam',127]}}},
 metal2:{name:'ダブルキック締め',genre:'メタル',length:4,difficulty:'上級',description:'キック連打とスネアフラムで強く次の小節へ入る。',pattern:{kick:[0,1,2,3],snare:[2,3],crash:[3]},meta:{kick:{0:['accent',120],1:['normal',112],2:['accent',124],3:['normal',118]},snare:{2:['roll',116],3:['flam',127]},crash:{3:['accent',127]}}},
 jazz1:{name:'ジャズ・コンピング',genre:'ジャズ',length:4,difficulty:'中級',description:'スネアのゴーストとタムで会話する短いジャズフィル。',pattern:{snare:[0,2],highTom:[1],floorTom:[3]},meta:{snare:{0:['ghost',46],2:['accent',82]},highTom:{1:['ghost',58]},floorTom:{3:['flam',94]}}},
 jazz2:{name:'スウィング・トリプレット風',genre:'ジャズ',length:8,difficulty:'上級',description:'強弱差を大きく付けたスネアとタムのスウィング系フィル。',pattern:{snare:[0,2,3,5,7],highTom:[1,4],floorTom:[6]},meta:{snare:{0:['accent',92],2:['ghost',46],3:['normal',72],5:['ghost',50],7:['flam',104]},highTom:{1:['ghost',58],4:['normal',78]},floorTom:{6:['accent',88]}}},
 latin1:{name:'ティンバレス・ブレイク',genre:'ラテン',length:8,difficulty:'中級',description:'ティンバレスとコンガを交互に鳴らすラテン系のおかず。',pattern:{timbale:[0,2,4,6],conga:[1,3,5,7],cowbell:[0,4]},meta:{timbale:{0:['accent',108],4:['accent',112],6:['roll',114]},conga:{1:['ghost',66],3:['normal',82],5:['ghost',68],7:['flam',112]},cowbell:{0:['accent',92],4:['accent',94]}}},
 latin2:{name:'サンバ・パーカッション',genre:'ラテン',length:16,difficulty:'上級',description:'複数の打楽器を重ねた1小節のサンバ系フィル。',pattern:{timbale:[0,3,6,9,12,15],conga:[1,4,7,10,13],highTom:[2,5,8,11,14],tambourine:[0,4,8,12]},meta:{timbale:{0:['accent',108],6:['roll',104],12:['accent',114],15:['flam',122]},conga:{1:['ghost',62],7:['accent',94],13:['accent',98]},highTom:{5:['accent',92],11:['accent',98],14:['roll',108]}}},
 edm1:{name:'ビルドアップ・スネア',genre:'EDM',length:16,difficulty:'中級',description:'ベロシティを上げながら密度を増やす定番ビルドアップ。',pattern:{snare:[0,2,4,6,8,9,10,11,12,13,14,15],clap:[12,14,15]},meta:{snare:{0:['ghost',42],2:['normal',52],4:['normal',62],6:['normal',72],8:['normal',82],9:['normal',88],10:['normal',94],11:['normal',100],12:['accent',108],13:['accent',114],14:['roll',120],15:['flam',127]},clap:{12:['normal',92],14:['accent',108],15:['accent',120]}}},
 hiphop1:{name:'ブーンバップ・ターン',genre:'ヒップホップ',length:4,difficulty:'中級',description:'スネアのゴーストとキックの食い込みで作る短いターン。',pattern:{kick:[0,3],snare:[1,2,3],rim:[0]},meta:{kick:{0:['accent',108],3:['normal',96]},snare:{1:['ghost',44],2:['normal',82],3:['flam',112]},rim:{0:['ghost',52]}}},
 hiphop2:{name:'トラップ・ハットフィル',genre:'ヒップホップ',length:8,difficulty:'上級',description:'ハイハットロールとオープンハットを組み合わせる。',pattern:{closedHat:[0,1,2,3,4,5,6,7],openHat:[6],snare:[7]},meta:{closedHat:{0:['normal',72],1:['ghost',52],2:['roll',84],3:['normal',76],4:['roll',94],5:['ghost',60],6:['accent',108],7:['roll',116]},openHat:{6:['accent',112]},snare:{7:['flam',118]}}},
 odd1:{name:'5拍子タム区切り',genre:'変拍子',length:8,difficulty:'上級',description:'3+2のまとまりをアクセントで示す変拍子向けフィル。',pattern:{highTom:[0,1,2],midTom:[3,4],floorTom:[5,6,7]},meta:{highTom:{0:['accent',108]},midTom:{3:['accent',112]},floorTom:{5:['accent',118],7:['flam',124]}}}
};

function insertDrumFillUI(){
 const sequencerPanel=document.querySelector('.sequencer-panel');if(!sequencerPanel)return;
 const section=document.createElement('section');section.className='panel drum-fill-panel';section.id='drumFillLibrary';
 section.innerHTML=`<div class="fill-header"><div><span class="section-kicker">DRUM FILL LAB</span><h2>ドラムのおかず</h2><p>フィルを選んで試聴し、現在のビート後半へ追加できるよ。</p></div><span id="fillCount"></span></div><div class="fill-controls"><label><span>ジャンル</span><select id="fillGenre"><option value="all">すべて</option></select></label><label><span>長さ</span><select id="fillLength"><option value="all">すべて</option><option value="4">1拍</option><option value="8">2拍</option><option value="16">1小節</option></select></label><label><span>追加方法</span><select id="fillApplyMode"><option value="replace">後半を置き換える</option><option value="merge">現在のビートへ重ねる</option></select></label></div><div id="fillCards" class="fill-cards"></div>`;
 sequencerPanel.insertAdjacentElement('afterend',section);
 const genres=[...new Set(Object.values(drumFills).map(x=>x.genre))];const genre=document.querySelector('#fillGenre');genres.forEach(g=>genre.add(new Option(g,g)));
 genre.addEventListener('change',renderFillCards);document.querySelector('#fillLength').addEventListener('change',renderFillCards);renderFillCards();
}
function filteredFills(){const g=document.querySelector('#fillGenre')?.value||'all',l=document.querySelector('#fillLength')?.value||'all';return Object.entries(drumFills).filter(([,f])=>(g==='all'||f.genre===g)&&(l==='all'||String(f.length)===l))}
function renderFillCards(){const list=filteredFills();document.querySelector('#fillCount').textContent=`${list.length}種類`;document.querySelector('#fillCards').innerHTML=list.map(([id,f])=>`<article class="fill-card"><div class="fill-tags"><span>${f.genre}</span><span>${f.length===4?'1拍':f.length===8?'2拍':'1小節'}</span><span>${f.difficulty}</span></div><h3>${f.name}</h3><p>${f.description}</p><div class="fill-actions"><button type="button" data-preview-fill="${id}">試聴</button><button type="button" data-apply-fill="${id}" class="fill-primary">ビートへ追加</button></div></article>`).join('');document.querySelectorAll('[data-preview-fill]').forEach(b=>b.onclick=()=>previewFill(b.dataset.previewFill));document.querySelectorAll('[data-apply-fill]').forEach(b=>b.onclick=()=>applyFill(b.dataset.applyFill))}
function fillMeta(fill,track,local){const item=fill.meta?.[track]?.[local];return item?{expression:item[0],velocity:item[1]}:{expression:'normal',velocity:100}}
function applyFill(id,preview=false){const fill=drumFills[id];if(!fill)return;ensureAudio();if(state.isPlaying)stop();const n=effectiveSteps();const start=Math.max(0,n-fill.length);const mode=document.querySelector('#fillApplyMode')?.value||'replace';if(mode==='replace'&&!preview){tracks.forEach(t=>{for(let i=start;i<n;i++){state.pattern[t.id][i]=false;setStepMeta(t.id,i,{expression:'normal',velocity:100})}})}Object.entries(fill.pattern).forEach(([track,steps])=>steps.forEach(local=>{const target=start+local;if(target<n){state.pattern[track][target]=true;setStepMeta(track,target,fillMeta(fill,track,local))}}));state.selectedPreset=null;renderPattern();if(!preview){els.title.textContent=fill.name;els.text.textContent=fill.description;els.tags.innerHTML=`<span>フィルイン</span><span>${fill.genre}</span><span>${fill.difficulty}</span>`}}
function previewFill(id){const fill=drumFills[id];if(!fill)return;const backup={pattern:structuredClone(state.pattern),stepData:structuredClone(performanceState.stepData),selected:state.selectedPreset};applyFill(id,true);state.currentStep=Math.max(0,effectiveSteps()-fill.length);start();setTimeout(()=>{stop();state.pattern=backup.pattern;performanceState.stepData=backup.stepData;state.selectedPreset=backup.selected;renderPattern()},Math.max(1200,fill.length*60000/state.bpm/4+250))}
insertDrumFillUI();