const learningProfiles={
 'ロック':{artists:'The Beatles、Nirvana、Green Day',instruments:'キックが土台、スネアが2・4拍のバックビート、ハイハットが細分を示す。',beginner:'まずキックとスネアだけを聴き、2・4拍で手拍子しよう。',intermediate:'ハイハットの開閉やキックの追加位置を比較しよう。',advanced:'ゴースト、フラム、ベロシティ差でダイナミクスを作ろう。'},
 'ポップス':{artists:'Michael Jackson、Bruno Mars、Official髭男dism',instruments:'歌を邪魔しない安定したキックとスネアが中心。ハイハットが曲の明るさを整える。',beginner:'8分のハイハットを一定に保とう。',intermediate:'キックの追加位置とクラップの重なりを聴こう。',advanced:'小さな強弱差とHumanizeで自然な伴奏を作ろう。'},
 'EDM':{artists:'Daft Punk、Avicii、The Chemical Brothers',instruments:'4つ打ちキックが脈を作り、クラップと裏拍ハイハットがダンス感を作る。',beginner:'毎拍のキックを数えながら聴こう。',intermediate:'裏拍のオープンハイハットを口で歌おう。',advanced:'開閉ハイハットとベロシティ差で展開を作ろう。'},
 'ヒップホップ':{artists:'A Tribe Called Quest、J Dilla、Kendrick Lamar',instruments:'キックのシンコペーション、重いスネア、細かなハイハットが中心。',beginner:'スネア位置を先に覚えよう。',intermediate:'Swingを変えてノリの差を比べよう。',advanced:'ゴーストとロール、Humanizeでポケットを作ろう。'},
 'ジャズ':{artists:'Art Blakey、Miles Davis、Herbie Hancock',instruments:'ライドが時間を示し、ペダルハイハットとスネアが会話を作る。',beginner:'ライドだけを聴いて跳ねを感じよう。',intermediate:'2・4拍のペダルハイハットを加えよう。',advanced:'強弱を固定せず、応答するようにゴーストを置こう。'},
 'ラテン':{artists:'Tito Puente、Santana、Sergio Mendes',instruments:'クラーベが基準線、コンガやティンバレスが異なる周期を重ねる。',beginner:'クラーベだけを手拍子しよう。',intermediate:'キックとクラーベを同時に感じよう。',advanced:'複数打楽器のベロシティを分けて層を作ろう。'},
 'ブルース':{artists:'B.B. King、Muddy Waters、Stevie Ray Vaughan',instruments:'シャッフルするハイハットと強いバックビートが土台。',beginner:'まっすぐとSwingを聴き比べよう。',intermediate:'3連の長短を声に出そう。',advanced:'ゴーストスネアで跳ねを保とう。'},
 'ワールド':{artists:'Bob Marley、Fela Kuti、Youssou N’Dour',instruments:'裏拍や複数の反復周期が独特の重心を作る。',beginner:'強拍以外に重心があることを感じよう。',intermediate:'各打楽器を1つずつ聴き分けよう。',advanced:'複数の周期とHumanizeを同時に扱おう。'},
 '変拍子':{artists:'Dave Brubeck、Tool、King Crimson',instruments:'アクセントのまとまりが拍子を理解する手がかりになる。',beginner:'拍を2+2+3などに分けて数えよう。',intermediate:'キックのアクセントだけで拍子を感じよう。',advanced:'フラムやフィルを入れても周期を見失わないようにしよう。'}
};
const learningState={level:'beginner',quiz:null};
function currentLearningPreset(){return presets[state.selectedPreset]||presets[document.querySelector('#presetSelect')?.value]||presets.basic8}
function profileFor(p){return learningProfiles[p.category]||learningProfiles['ポップス']}
function renderLearning(){const p=currentLearningPreset(),profile=profileFor(p);if(!p)return;document.querySelector('#learningRhythmTitle').textContent=p.name;document.querySelector('#learningRhythmExplanation').textContent=p.lesson;document.querySelector('#learningInstrumentExplanation').textContent=profile.instruments;document.querySelector('#learningGenreText').textContent=`${p.category}でよく使われるリズム。代表例：${profile.artists}`;document.querySelector('#learningLevelText').textContent=profile[learningState.level];document.querySelector('#learningMeta').innerHTML=[p.category,p.meter,`BPM ${p.bpm}`,p.difficulty].map(x=>`<span>${x}</span>`).join('');renderComparison(p);}
function renderComparison(p){const entries=Object.entries(presets).filter(([id,x])=>id!==state.selectedPreset&&(x.category===p.category||x.meter===p.meter));const other=(entries[Math.floor(Math.random()*entries.length)]||Object.entries(presets)[0]);const target=document.querySelector('#compareContent');target.innerHTML=`<div class="compare-rhythm"><strong>${p.name}</strong><span>${p.feature}</span></div><div class="compare-vs">VS</div><div class="compare-rhythm"><strong>${other[1].name}</strong><span>${other[1].feature}</span></div>`;}
function newQuiz(){const p=currentLearningPreset();const pool=Object.values(presets).filter(x=>x!==p);const wrong=[...pool].sort(()=>Math.random()-.5).slice(0,3);const choices=[p,...wrong].sort(()=>Math.random()-.5);learningState.quiz={answer:p.name};document.querySelector('#quizQuestion').textContent=`「${p.feature}」に当てはまるリズムはどれ？`;document.querySelector('#quizOptions').innerHTML=choices.map(x=>`<button class="quiz-option" data-answer="${x.name}">${x.name}</button>`).join('');document.querySelector('#quizResult').textContent='';document.querySelectorAll('.quiz-option').forEach(b=>b.addEventListener('click',()=>answerQuiz(b)));}
function answerQuiz(button){const ok=button.dataset.answer===learningState.quiz.answer;document.querySelectorAll('.quiz-option').forEach(b=>{b.disabled=true;if(b.dataset.answer===learningState.quiz.answer)b.classList.add('is-correct')});document.querySelector('#quizResult').textContent=ok?'正解！特徴と音を結びつけられてるよ。':`惜しい！正解は「${learningState.quiz.answer}」。`;}
document.querySelectorAll('[data-learning-level]').forEach(btn=>btn.addEventListener('click',()=>{learningState.level=btn.dataset.learningLevel;document.querySelectorAll('[data-learning-level]').forEach(x=>x.classList.toggle('is-selected',x===btn));renderLearning()}));document.querySelector('#newQuizButton')?.addEventListener('click',newQuiz);document.querySelector('#refreshCompareButton')?.addEventListener('click',()=>renderComparison(currentLearningPreset()));const previousLearningLoad=loadPreset;loadPreset=function(id){previousLearningLoad(id);renderLearning();newQuiz()};renderLearning();newQuiz();