(()=>{
const PAD_IDS=['crash','ride','highTom','midTom','floorTom','closedHat','snare','kick'];
const MIDI={kick:36,snare:38,clap:39,rim:37,side:37,closedHat:42,openHat:46,pedalHat:44,highTom:50,midTom:47,floorTom:43,crash:49,ride:51,splash:55,china:52,cowbell:56,tambourine:54,shaker:70,conga:64,bongo:60,timbale:65,claves:75,woodBlock:76,triangle:81};
const detail={timing:0,velocity:0,random:0,hand:0};
const node=(tag,cls,html='')=>{const n=document.createElement(tag);n.className=cls||'';n.innerHTML=html;return n};
const saveBlob=(blob,name)=>{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};
function flash(id){const b=document.querySelector(`.drum-pad[data-track="${id}"]`);if(!b)return;b.classList.add('is-hit');setTimeout(()=>b.classList.remove('is-hit'),110)}
function buildPads(){const w=document.querySelector('#drumPads');w.innerHTML='';PAD_IDS.forEach(id=>{const t=tracks.find(x=>x.id===id);if(!t)return;const b=node('button','drum-pad',`<span>${t.icon}</span><strong>${t.name}</strong><small>Tap</small>`);b.dataset.track=id;b.style.setProperty('--pad-color',t.color);b.onclick=()=>{ensureAudio();triggerSound(id,state.audioContext.currentTime,{expression:'normal',velocity:performanceState.velocity||100});flash(id)};w.append(b)})}
function buildRoll(){const w=document.querySelector('#pianoRoll');if(!w)return;const steps=effectiveSteps();w.style.setProperty('--steps',steps);w.innerHTML='';tracks.forEach(t=>{const r=node('div','piano-row');r.append(node('div','piano-name',t.name));for(let i=0;i<steps;i++){const c=node('button','piano-cell');c.style.setProperty('--cell-color',t.color);c.classList.toggle('is-on',!!state.pattern[t.id]?.[i]);c.onclick=()=>{toggleStep(t.id,i,c);buildRoll()};r.append(c)}w.append(r)})}
function buildHumanize(){const w=document.querySelector('#humanizeGrid'),defs=[['timing','Timing','ms',30],['velocity','Velocity','%',40],['random','Random','%',35],['hand','左右の手','%',30]];w.innerHTML='';defs.forEach(([k,label,suffix,max])=>{const l=node('label','humanize-control',`<span>${label} <strong>${detail[k]}${suffix}</strong></span><input type="range" min="0" max="${max}" value="${detail[k]}">`);l.querySelector('input').oninput=e=>{detail[k]=+e.target.value;l.querySelector('strong').textContent=`${detail[k]}${suffix}`;localStorage.setItem('rhythmLabHumanizeDetail',JSON.stringify(detail))};w.append(l)})}
function install(){if(document.querySelector('#rhythmTools'))return;const host=document.querySelector('.sequencer-panel');if(!host)return;const root=node('section','rhythm-tools panel',`<article class="tool-card"><div class="tool-head"><div><span class="section-kicker">LIVE DRUM</span><h2>ドラムセット演奏</h2><p>タップで演奏。再生中の音も光るよ。</p></div></div><div class="drum-pads" id="drumPads"></div></article><article class="tool-card"><div class="tool-head"><div><span class="section-kicker">PIANO ROLL</span><h2>DAW表示</h2><p>マスを直接タップして編集できる。</p></div></div><div class="piano-roll-wrap"><div class="piano-roll" id="pianoRoll"></div></div></article><article class="tool-card"><div class="tool-head"><div><span class="section-kicker">HUMANIZE</span><h2>演奏の揺れを細かく調整</h2></div></div><div class="humanize-grid" id="humanizeGrid"></div></article><article class="tool-card"><div class="tool-head"><div><span class="section-kicker">EXPORT</span><h2>書き出し</h2></div></div><div class="export-actions"><button id="exportMidi">MIDIを書き出す</button><button id="exportWav">WAVを書き出す</button><button id="exportMp3">MP3を書き出す</button></div><p class="export-note" id="exportNote">MP3は対応ブラウザのみ利用できるよ。</p></article>`);host.insertAdjacentElement('afterend',root);buildPads();buildRoll();buildHumanize();bindExports()}
try{Object.assign(detail,JSON.parse(localStorage.getItem('rhythmLabHumanizeDetail'))||{})}catch{}
if(typeof humanized==='function'){const baseHumanized=humanized;humanized=function(time,meta){const b=baseHumanized(time,meta),timing=(Math.random()*2-1)*detail.timing/1000,vel=1+(Math.random()*2-1)*detail.velocity/100,random=Math.random()<detail.random/100?.82:1,hand=1+((Math.random()>.5?1:-1)*detail.hand/500);return {time:Math.max(state.audioContext.currentTime,b.time+timing),gain:b.gain*vel*random*hand}}}
const oldRender=renderPattern;renderPattern=function(){oldRender();buildRoll()};const oldStep=playCurrentStep;playCurrentStep=function(){const i=state.currentStep;tracks.forEach(t=>state.pattern[t.id]?.[i]&&flash(t.id));oldStep()};
function vlq(n){const a=[];do{let b=n&127;n>>=7;if(a.length)b|=128;a.unshift(b)}while(n);return a}function u32(n){return[(n>>>24)&255,(n>>>16)&255,(n>>>8)&255,n&255]}
function midiBlob(){const ppq=96,step=24,ev=[];tracks.forEach(t=>(state.pattern[t.id]||[]).forEach((on,i)=>{if(!on)return;const note=MIDI[t.id]||60,vel=Math.max(1,Math.min(127,getStepMeta(t.id,i)?.velocity||100)),tick=i*step;ev.push({tick,data:[0x99,note,vel]},{tick:tick+16,data:[0x89,note,0]})}));ev.sort((a,b)=>a.tick-b.tick);let body=[],last=0,mpqn=Math.round(60000000/state.bpm);body.push(0,255,81,3,(mpqn>>16)&255,(mpqn>>8)&255,mpqn&255);ev.forEach(e=>{body.push(...vlq(e.tick-last),...e.data);last=e.tick});body.push(0,255,47,0);return new Blob([new Uint8Array([77,84,104,100,0,0,0,6,0,0,0,1,0,ppq,77,84,114,107,...u32(body.length),...body])],{type:'audio/midi'})}
function wavBlob(){const sr=44100,stepSec=60/state.bpm/4,len=Math.ceil((effectiveSteps()*stepSec+.7)*sr),mix=new Float32Array(len);tracks.forEach((t,ti)=>(state.pattern[t.id]||[]).forEach((on,i)=>{if(!on)return;const start=Math.floor(i*stepSec*sr),amp=(getStepMeta(t.id,i)?.velocity||100)/127*.42;for(let n=0;n<Math.min(sr*.5,len-start);n++){const x=n/sr,env=Math.exp(-x*(t.type==='cymbal'?7:t.type==='kick'?12:22));const s=t.type==='kick'?Math.sin(2*Math.PI*(55+70*Math.exp(-x*25))*x):(['noise','hat','cymbal'].includes(t.type)?Math.random()*2-1:Math.sin(2*Math.PI*(110+ti*18)*x));mix[start+n]+=s*env*amp}}));const b=new ArrayBuffer(44+len*2),v=new DataView(b),w=(o,s)=>[...s].forEach((c,i)=>v.setUint8(o+i,c.charCodeAt(0)));w(0,'RIFF');v.setUint32(4,36+len*2,true);w(8,'WAVEfmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,sr,true);v.setUint32(28,sr*2,true);v.setUint16(32,2,true);v.setUint16(34,16,true);w(36,'data');v.setUint32(40,len*2,true);for(let i=0;i<len;i++)v.setInt16(44+i*2,Math.max(-1,Math.min(1,mix[i]))*32767,true);return new Blob([b],{type:'audio/wav'})}
async function mp3(){const note=document.querySelector('#exportNote');if(!window.MediaRecorder||!MediaRecorder.isTypeSupported('audio/mpeg')){note.textContent='このブラウザはMP3録音に未対応。WAVを使ってね。';return}ensureAudio();const d=state.audioContext.createMediaStreamDestination();state.masterGain.connect(d);const r=new MediaRecorder(d.stream,{mimeType:'audio/mpeg'}),parts=[];r.ondataavailable=e=>e.data.size&&parts.push(e.data);r.onstop=()=>saveBlob(new Blob(parts,{type:'audio/mpeg'}),'rhythm-lab.mp3');r.start();const was=state.isPlaying;if(!was)play();setTimeout(()=>{r.stop();if(!was&&state.isPlaying)stop()},effectiveSteps()*60/state.bpm/4*1000+250)}
function bindExports(){document.querySelector('#exportMidi').onclick=()=>saveBlob(midiBlob(),'rhythm-lab.mid');document.querySelector('#exportWav').onclick=()=>saveBlob(wavBlob(),'rhythm-lab.wav');document.querySelector('#exportMp3').onclick=mp3}
setTimeout(install,0);
})();