(()=>{
const PAD_IDS=['crash','ride','highTom','midTom','floorTom','closedHat','snare','kick'];
const MIDI_NOTES={kick:36,snare:38,clap:39,rim:37,side:37,closedHat:42,openHat:46,pedalHat:44,highTom:50,midTom:47,floorTom:43,crash:49,ride:51,splash:55,china:52,cowbell:56,tambourine:54,shaker:70,conga:64,bongo:60,timbale:65,claves:75,woodBlock:76,triangle:81};
const humanizeDetail={timing:0,velocity:0,random:0,hand:0};
function el(tag,cls,html){const n=document.createElement(tag);if(cls)n.className=cls;if(html!==undefined)n.innerHTML=html;return n}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.append(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},800)}
function installUI(){if(document.querySelector('#rhythmTools'))return;const host=document.querySelector('.sequencer-panel');if(!host)return;const root=el('section','rhythm-tools panel');root.id='rhythmTools';root.innerHTML=`<article class="tool-card"><div class="tool-head"><div><span class="section-kicker">LIVE DRUM</span><h2>ドラムセット演奏</h2><p>パッドをタップするとすぐ鳴る。再生中の音も光るよ。</p></div></div><div class="drum-pads" id="drumPads"></div></article><article class="tool-card"><div class="tool-head"><div><span class="section-kicker">PIANO ROLL</span><h2>DAW表示</h2><p>マスを直接タップして編集できる。</p></div></div><div class="piano-roll-wrap"><div class="piano-roll" id="pianoRoll"></div></div></article><article class="tool-card"><div class="tool-head"><div><span class="section-kicker">HUMANIZE</span><h2>演奏の揺れを細かく調整</h2></div></div><div class="humanize-grid" id="humanizeGrid"></div></article><article class="tool-card"><div class="tool-head"><div><span class="section-kicker">EXPORT</span><h2>書き出し</h2><p>作ったビートをDAWやスマホで使える形式に保存。</p></div></div><div class="export-actions"><button id="exportMidi">MIDIを書き出す</button><button id="exportWav">WAVを書き出す</button><button id="exportMp3">MP3を書き出す</button></div><p class="export-note" id="exportNote">MP3はブラウザがaudio/mpeg録音に対応している場合のみ利用できるよ。</p></article>`;host.insertAdjacentElement('afterend',root);buildPads();buildPiano();buildHumanize();bindExports();}
function buildPads(){const wrap=document.querySelector('#drumPads');wrap.innerHTML='';PAD_IDS.forEach(id=>{const t=tracks.find(x=>x.id===id);if(!t)return;const b=el('button','drum-pad',`<span>${t.icon}</span><strong>${t.name}</strong><small>Tap</small>`);b.type='button';b.style.setProperty('--pad-color',t.color);b.addEventListener('pointerdown',()=>{ensureAudio();triggerSound(id,state.audioContext.currentTime,{expression:'normal',velocity:performanceState.velocity||100});flashPad(id)});wrap.append(b);b.dataset.track=id})}
function flashPad(id){const b=document.querySelector(`.drum-pad[data-track="${id}"]`);if(!b)return;b.classList.add('is-hit');setTimeout(()=>b.classList.remove('is-hit'),110)}
function buildPiano(){const roll=document.querySelector('#pianoRoll');if(!roll)return;const steps=effectiveSteps();roll.style.setProperty('--steps',steps);roll.innerHTML='';tracks.forEach(t=>{const row=el('div','piano-row');row.dataset.track=t.id;row.append(el('div','piano-name',t.name));for(let i=0;i<steps;i++){const c=el('button','piano-cell');c.type='button';c.style.setProperty('--cell-color',t.color);c.classList.toggle('is-on',!!state.pattern[t.id]?.[i]);c.addEventListener('click',()=>{toggleStep(t.id,i,c);buildPiano()});row.append(c)}roll.append(row)})}
function buildHumanize(){const wrap=document.querySelector('#humanizeGrid');const defs=[['timing','Timing','ms',0,30],['velocity','Velocity','%',0,40],['random','Random','%',0,35],['hand','左右の手','%',0,30]];wrap.innerHTML='';defs.forEach(([key,label,suffix,min,max])=>{const l=el('label','humanize-control',`<span>${label} <strong>${humanizeDetail[key]}${suffix}</strong></span><input type="range" min="${min}" max="${max}" value="${humanizeDetail[key]}">`);l.querySelector('input').addEventListener('input',e=>{humanizeDetail[key]=+e.target.value;l.querySelector('strong').textContent=`${e.target.value}${suffix}`;localStorage.setItem('rhythmLabHumanizeDetail',JSON.stringify(humanizeDetail))});wrap.append(l)})}
function restoreHumanize(){try{Object.assign(humanizeDetail,JSON.parse(localStorage.getItem('rhythmLabHumanizeDetail'))||{})}catch{}}
const previousHumanized=typeof humanized==='function'?humanized:null;if(previousHumanized){humanized=function(time,meta){const base=previousHumanized(time,meta),timing=(Math.random()*2-1)*humanizeDetail.timing/1000,velocity=1+(Math.random()*2-1)*humanizeDetail.velocity/100,random=Math.random()<humanizeDetail.random/100?.82:1,hand=1+((Math.random()>.5?1:-1)*humanizeDetail.hand/500);return {time:Math.max(state.audioContext.currentTime,base.time+timing),gain:base.gain*velocity*random*hand}}}
const oldRender=renderPattern;renderPattern=function(){oldRender();buildPiano()};const oldPlay=playCurrentStep;playCurrentStep=function(){const current=state.currentStep;tracks.forEach(t=>state.pattern[t.id]?.[current]&&flashPad(t.id));oldPlay()};
function varLen(v){const a=[];let n=v;do{let b=n&127;n>>=7;if(a.length)b|=128;a.unshift(b)}while(n);return a}
function u32(n){return[(n>>>24)&255,(n>>>16)&255,(n>>>8)&255,n&255]}
function midiBytes(){const ppq=96,events=[],stepTicks=ppq/4;tracks.forEach(t=>(state.pattern[t.id]||[]).forEach((on,i)=>{if(!on)return;const note=MIDI_NOTES[t.id]||60,vel=Math.max(1,Math.min(127,getStepMeta?.(t.id,i)?.velocity||100)),tick=Math.round(i*stepTicks);events.push({tick,data:[0x99,note,vel]},{tick:tick+Math.round(stepTicks*.65),data:[0x89,note,0]})}));events.sort((a,b)=>a.tick-b.tick);let body=[],last=0;const mpqn=Math.round(60000000/state.bpm);body.push(0,0xff,0x51,3,(mpqn>>16)&255,(mpqn>>8)&255,mpqn&255);events.forEach(e=>{body.push(...varLen(e.tick-last),...e.data);last=e.tick});body.push(0,0xff,0x2f,0);return new Uint8Array([77,84,104,100,0,0,0,6,0,0,0,1,0,ppq,77,84,114,107,...u32(body.length),...body])}
function synthWav(){const sr=44100,steps=effectiveSteps(),stepSec=60/state.bpm/4,dur=steps*stepSec+.7,len=Math.ceil(sr*dur),mix=new Float32Array(len);tracks.forEach((t,ti)=>(state.pattern[t.id]||[]).forEach((on,i)=>{if(!on)return;const start=Math.floor(i*stepSec*sr),meta=getStepMeta?.(t.id,i)||{velocity:100},amp=(meta.velocity||100)/127*.45;for(let n=0;n<Math.min(sr*.5,len-start);n++){const x=n/sr,env=Math.exp(-x*(t.type==='cymbal'?7:t.type==='kick'?12:22));let s;if(t.type==='kick')s=Math.sin(2*Math.PI*(55+70*Math.exp(-x*25))*x);else if(['noise','hat','cymbal'].includes(t.type))s=(Math.random()*2-1);else s=Math.sin(2*Math.PI*(110+ti*18)*x);mix[start+n]+=s*env*amp}}));const buffer=new ArrayBuffer(44+len*2),v=new DataView(buffer);const w=(o,s)=>[...s].forEach((c,i)=>v.setUint8(o+i,c.charCodeAt(0)));w(0,'RIFF');v.setUint32(4,36+len*2,true);w(8,'WAVEfmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,sr,true);v.setUint32(28,sr*2,true);v.setUint16(32,2,true);v.setUint16(34,16,true);w(36,'data');v.setUint32(40,len*2,true);for(let i=0;i<len;i++)v.setInt16(44+i*2,Math.max(-1,Math.min(1,mix[i]))*32767,true);return new Blob([buffer],{type:'audio/wav'})}
async function exportMp3(){if(!window.MediaRecorder||!MediaRecorder.isTypeSupported('audio/mpeg')){document.querySelector('#exportNote').textContent='このブラウザはMP3録音に未対応。WAV書き出しを使ってね。';return}ensureAudio();const dest=state.audioContext.createMediaStreamDestination();state.masterGain.connect(dest);const rec=new MediaRecorder(dest.stream,{mimeType:'audio/mpeg'}),chunks=[];rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);rec.onstop=()=>download(new Blob(chunks,{type:'audio/mpeg'}),'rhythm-lab.mp3');rec.start();const was=state.isPlaying;if(!was)play();setTimeout(()=>{rec.stop();if(!was&&state.isPlaying)stop()},effectiveSteps()*60/state.bpm/4*1000+250)}
function bindExports(){document.querySelector('#exportMidi').onclick=()=>download(new Blob([midiBytes()],{type:'audio/midi'}),'rhythm-lab.mid');document.querySelector('#exportWav').onclick=()=>download(synthWav(),'rhythm-lab.wav');document.querySelector('#exportMp3').onclick=exportMp3}
restoreHumanize();setTimeout(installUI,0);
})();