const trackMixerState={};
const velocityLayers={soft:{label:'Soft',min:0,max:55,amp:.68,pitch:.985,decay:1.12},medium:{label:'Medium',min:56,max:99,amp:.9,pitch:1,decay:1},hard:{label:'Hard',min:100,max:119,amp:1.08,pitch:1.012,decay:.94},rimshot:{label:'Rimshot',min:120,max:127,amp:1.18,pitch:1.025,decay:.88}};
const dedicatedAcousticTracks=new Set(['kick','snare','closedHat','openHat','ride','crash','highTom','midTom','floorTom','rim']);
function defaultTrackMixer(){return {volume:100,pan:0,mute:false,solo:false,pitch:0,decay:100}}
function ensureTrackMixer(){tracks.forEach(t=>{if(!trackMixerState[t.id])trackMixerState[t.id]=defaultTrackMixer()})}
function velocityLayerFor(meta,id){const v=Math.max(0,Math.min(127,meta?.velocity??100));if((id==='rim'||id==='snare')&&v>=120)return velocityLayers.rimshot;return Object.values(velocityLayers).find(x=>v>=x.min&&v<=x.max)||velocityLayers.medium}
function hasSolo(){return Object.values(trackMixerState).some(x=>x.solo)}
function getTrackBus(id){ensureTrackMixer();const c=state.audioContext;if(!c)return state.masterGain;const m=trackMixerState[id];if(!m.bus||m.context!==c){const gain=c.createGain(),pan=typeof c.createStereoPanner==='function'?c.createStereoPanner():null;gain.connect(pan||state.masterGain);if(pan)pan.connect(state.masterGain);m.bus=gain;m.panNode=pan;m.context=c}const audible=!m.mute&&(!hasSolo()||m.solo);m.bus.gain.setTargetAtTime(audible?m.volume/100:0,c.currentTime,.008);if(m.panNode)m.panNode.pan.setTargetAtTime(m.pan/100,c.currentTime,.008);return m.bus}
function mixerProfile(profile,id,meta){const m=trackMixerState[id]||defaultTrackMixer(),layer=velocityLayerFor(meta,id);return {...profile,pitch:(profile.pitch||1)*layer.pitch*Math.pow(2,m.pitch/12),decay:(profile.decay||1)*layer.decay*(m.decay/100),velocityLayer:layer.label,dedicatedAcoustic:dedicatedAcousticTracks.has(id)}}
const velocityMixerTrigger=triggerSound;
triggerSound=function(id,time,meta={expression:'normal',velocity:100}){ensureTrackMixer();const m=trackMixerState[id];if(m.mute||(hasSolo()&&!m.solo))return;const layer=velocityLayerFor(meta,id);const oldMaster=state.masterGain;state.masterGain=getTrackBus(id);const oldKit=kitProfiles[performanceState.kit];kitProfiles[performanceState.kit]=mixerProfile(oldKit,id,meta);try{return velocityMixerTrigger(id,time,{...meta,velocity:Math.min(127,(meta.velocity??100)*layer.amp)})}finally{kitProfiles[performanceState.kit]=oldKit;state.masterGain=oldMaster}};
function mixerControl(label,type,value,min,max,step=1){const wrap=document.createElement('label');wrap.className='mixer-control';wrap.innerHTML=`<span>${label}</span><input type="${type}" value="${value}" min="${min}" max="${max}" step="${step}">`;return wrap}
function buildTrackMixer(){ensureTrackMixer();const advanced=document.querySelector('.advanced-panel');if(!advanced||document.querySelector('#trackMixer'))return;const section=document.createElement('section');section.id='trackMixer';section.className='track-mixer';section.innerHTML='<div class="mixer-heading"><div><strong>TRACK MIXER</strong><small>各楽器の音量・定位・音程・余韻を調整</small></div><span>Soft / Medium / Hard / Rimshot 対応</span></div><div class="mixer-scroll"><div class="mixer-list"></div></div>';const list=section.querySelector('.mixer-list');tracks.forEach(t=>{const m=trackMixerState[t.id],row=document.createElement('div');row.className='mixer-row';row.dataset.track=t.id;row.innerHTML=`<div class="mixer-name"><span style="--track-color:${t.color}">${t.icon}</span><strong>${t.name}</strong>${dedicatedAcousticTracks.has(t.id)?'<small>REAL 4-LAYER</small>':''}</div><div class="mixer-switches"><button type="button" data-mixer="mute">M</button><button type="button" data-mixer="solo">S</button></div>`;const volume=mixerControl('VOL','range',m.volume,0,120),pan=mixerControl('PAN','range',m.pan,-100,100),pitch=mixerControl('PITCH','range',m.pitch,-12,12),decay=mixerControl('DECAY','range',m.decay,20,200);[['volume',volume],['pan',pan],['pitch',pitch],['decay',decay]].forEach(([key,control])=>{control.querySelector('input').addEventListener('input',e=>{m[key]=+e.target.value;getTrackBus(t.id);saveTrackMixer()});row.appendChild(control)});row.querySelector('[data-mixer="mute"]').addEventListener('click',e=>{m.mute=!m.mute;e.currentTarget.classList.toggle('is-active',m.mute);refreshMixerBuses();saveTrackMixer()});row.querySelector('[data-mixer="solo"]').addEventListener('click',e=>{m.solo=!m.solo;e.currentTarget.classList.toggle('is-active',m.solo);refreshMixerBuses();saveTrackMixer()});list.appendChild(row)});advanced.appendChild(section)}
function refreshMixerBuses(){if(!state.audioContext)return;tracks.forEach(t=>getTrackBus(t.id))}
function saveTrackMixer(){const plain={};Object.entries(trackMixerState).forEach(([id,m])=>plain[id]={volume:m.volume,pan:m.pan,mute:m.mute,solo:m.solo,pitch:m.pitch,decay:m.decay});localStorage.setItem('rhythmLabTrackMixer',JSON.stringify(plain))}
function restoreTrackMixer(){try{const saved=JSON.parse(localStorage.getItem('rhythmLabTrackMixer'));if(saved)Object.entries(saved).forEach(([id,m])=>trackMixerState[id]={...defaultTrackMixer(),...m})}catch{}}
restoreTrackMixer();buildTrackMixer();
(()=>{if(document.querySelector('script[data-rhythm-suite]'))return;const css=document.createElement('link');css.rel='stylesheet';css.href='rhythm-tools.css?v=1';document.head.append(css);const script=document.createElement('script');script.src='rhythm-suite-v2.js?v=1';script.dataset.rhythmSuite='true';document.body.append(script)})();